//Maincatagory
export const CREATE_MAINCATAGORY= "CREATE_MAINCATAGORY"
export const CREATE_MAINCATAGORY_RED= "CREATE_MAINCATAGORY_RED"

export const GET_MAINCATAGORY= "GET_MAINCATAGORY"
export const GET_MAINCATAGORY_RED= "GET_MAINCATAGORY_RED"

export const UPDATE_MAINCATAGORY= "UPDATE_MAINCATAGORY"
export const UPDATE_MAINCATAGORY_RED= "UPDATE_MAINCATAGORY_RED"

export const DELETE_MAINCATAGORY= "DELETE_MAINCATAGORY"
export const DELETE_MAINCATAGORY_RED= "DELETE_MAINCATAGORY_RED"

//SUBCATAGORY
export const CREATE_SUBCATAGORY= "CREATE_SUBCATAGORY"
export const CREATE_SUBCATAGORY_RED= "CREATE_SUBCATAGORY_RED"

export const GET_SUBCATAGORY= "GET_SUBCATAGORY"
export const GET_SUBCATAGORY_RED= "GET_SUBCATAGORY_RED"

export const UPDATE_SUBCATAGORY= "UPDATE_SUBCATAGORY"
export const UPDATE_SUBCATAGORY_RED= "UPDATE_SUBCATAGORY_RED"

export const DELETE_SUBCATAGORY= "DELETE_SUBCATAGORY"
export const DELETE_SUBCATAGORY_RED= "DELETE_SUBCATAGORY_RED"

//BRAND
export const CREATE_BRAND= "CREATE_BRAND"
export const CREATE_BRAND_RED= "CREATE_BRAND_RED"

export const GET_BRAND= "GET_BRAND"
export const GET_BRAND_RED= "GET_BRAND_RED"

export const UPDATE_BRAND= "UPDATE_BRAND"
export const UPDATE_BRAND_RED= "UPDATE_BRAND_RED"

export const DELETE_BRAND= "DELETE_BRAND"
export const DELETE_BRAND_RED= "DELETE_BRAND_RED"

//PRODUCT
export const CREATE_PRODUCT= "CREATE_PRODUCT"
export const CREATE_PRODUCT_RED= "CREATE_PRODUCT_RED"

export const GET_PRODUCT= "GET_PRODUCT"
export const GET_PRODUCT_RED= "GET_PRODUCT_RED"

export const UPDATE_PRODUCT= "UPDATE_PRODUCT"
export const UPDATE_PRODUCT_RED= "UPDATE_PRODUCT_RED"

export const DELETE_PRODUCT= "DELETE_PRODUCT"
export const DELETE_PRODUCT_RED= "DELETE_PRODUCT_RED"

//FEATURE
export const CREATE_FEATURE= "CREATE_FEATURE"
export const CREATE_FEATURE_RED= "CREATE_FEATURE_RED"

export const GET_FEATURE= "GET_FEATURE"
export const GET_FEATURE_RED= "GET_FEATURE_RED"

export const UPDATE_FEATURE= "UPDATE_FEATURE"
export const UPDATE_FEATURE_RED= "UPDATE_FEATURE_RED"

export const DELETE_FEATURE= "DELETE_FEATURE"
export const DELETE_FEATURE_RED= "DELETE_FEATURE_RED"

//FAQ
export const CREATE_FAQ= "CREATE_FAQ"
export const CREATE_FAQ_RED= "CREATE_FAQ_RED"

export const GET_FAQ= "GET_FAQ"
export const GET_FAQ_RED= "GET_FAQ_RED"

export const UPDATE_FAQ= "UPDATE_FAQ"
export const UPDATE_FAQ_RED= "UPDATE_FAQ_RED"

export const DELETE_FAQ= "DELETE_FAQ"
export const DELETE_FAQ_RED= "DELETE_FAQ_RED"

//SETTING
export const CREATE_SETTING= "CREATE_SETTING"
export const CREATE_SETTING_RED= "CREATE_SETTING_RED"

export const GET_SETTING= "GET_SETTING"
export const GET_SETTING_RED= "GET_SETTING_RED"

export const UPDATE_SETTING= "UPDATE_SETTING"
export const UPDATE_SETTING_RED= "UPDATE_SETTING_RED"

export const DELETE_SETTING= "DELETE_SETTING"
export const DELETE_SETTING_RED= "DELETE_SETTING_RED"

//PRIVACYPOLICY
export const CREATE_PRIVACY_POLICY= "CREATE_PRIVACY_POLICY"
export const CREATE_PRIVACY_POLICY_RED= "CREATE_PRIVACY_POLICY_RED"

export const GET_PRIVACY_POLICY= "GET_PRIVACY_POLICY"
export const GET_PRIVACY_POLICY_RED= "GET_PRIVACY_POLICY_RED"

export const UPDATE_PRIVACY_POLICY= "UPDATE_PRIVACY_POLICY"
export const UPDATE_PRIVACY_POLICY_RED= "UPDATE_PRIVACY_POLICY_RED"

export const DELETE_PRIVACY_POLICY= "DELETE_PRIVACY_POLICY"
export const DELETE_PRIVACY_POLICY_RED= "DELETE_PRIVACY_POLICY_RED"

//TERMSCONDITION
export const CREATE_TERMS_CONDITIONS= "CREATE_TERMS_CONDITIONS"
export const CREATE_TERMS_CONDITIONS_RED= "CREATE_TERMS_CONDITIONS_RED"

export const GET_TERMS_CONDITIONS= "GET_TERMS_CONDITIONS"
export const GET_TERMS_CONDITIONS_RED= "GET_TERMS_CONDITIONS_RED"

export const UPDATE_TERMS_CONDITIONS= "UPDATE_TERMS_CONDITIONS"
export const UPDATE_TERMS_CONDITIONS_RED= "UPDATE_TERMS_CONDITIONS_RED"

export const DELETE_TERMS_CONDITIONS= "DELETE_TERMS_CONDITIONS"
export const DELETE_TERMS_CONDITIONS_RED= "DELETE_TERMS_CONDITIONS_RED"

// CART
export const CREATE_CART = "CREATE_CART"
export const CREATE_CART_RED = "CREATE_CART_RED"

export const GET_CART = "GET_CART"
export const GET_CART_RED = "GET_CART_RED"

export const UPDATE_CART = "UPDATE_CART"
export const UPDATE_CART_RED = "UPDATE_CART_RED"

export const DELETE_CART = "DELETE_CART"
export const DELETE_CART_RED = "DELETE_CART_RED"

//CheckOut

export const CREATE_CHECKOUT = "CREATE_CHECKOUT"
export const CREATE_CHECKOUT_RED = "CREATE_CHECKOUT_RED"

export const GET_CHECKOUT = "GET_CHECKOUT"
export const GET_CHECKOUT_RED = "GET_CHECKOUT_RED"

export const UPDATE_CHECKOUT = "UPDATE_CHECKOUT"
export const UPDATE_CHECKOUT_RED = "UPDATE_CHECKOUT_RED"

export const DELETE_CHECKOUT = "DELETE_CHECKOUT"
export const DELETE_CHECKOUT_RED = "DELETE_CHECKOUT_RED"

// Wishlist
export const CREATE_WISHLIST = "CREATE_WISHLIST"
export const CREATE_WISHLIST_RED = "CREATE_WISHLIST_RED"

export const GET_WISHLIST = "GET_WISHLIST"
export const GET_WISHLIST_RED = "GET_WISHLIST_RED"

export const UPDATE_WISHLIST = "UPDATE_WISHLIST"
export const UPDATE_WISHLIST_RED = "UPDATE_WISHLIST_RED"

export const DELETE_WISHLIST = "DELETE_WISHLIST"
export const DELETE_WISHLIST_RED = "DELETE_WISHLIST_RED"


// Testimonial
export const CREATE_TESTIMONIAL = "CREATE_TESTIMONIAL"
export const CREATE_TESTIMONIAL_RED = "CREATE_TESTIMONIAL_RED"

export const GET_TESTIMONIAL = "GET_TESTIMONIAL"
export const GET_TESTIMONIAL_RED = "GET_TESTIMONIAL_RED"

export const UPDATE_TESTIMONIAL = "UPDATE_TESTIMONIAL"
export const UPDATE_TESTIMONIAL_RED = "UPDATE_TESTIMONIAL_RED"

export const DELETE_TESTIMONIAL = "DELETE_TESTIMONIAL"
export const DELETE_TESTIMONIAL_RED = "DELETE_TESTIMONIAL_RED"

